### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by timstott** [timstott/lotus-rouge#1]
My dear friends, @samuelmolinari @joejeet @patrickjandrews @barodeur, it time for us to unite and build the most epic site of the internets.

Today Ellen has the upper hand when it comes to pranking, but it's about to change.

Chuangs Laundry is Ellen's fabricated laundry business. We intend to launch the fake business in the coming weeks, promotional material would include the site [chuangslaundry.asia](http://chuangslaundry.asia), Twitter and Facebook campaigns and probably flyers.

About the site, it only consists of one page (KISS), laid out using tables, marquee tags all over the place, it needs to be dreadful.

Share ideas, feel free to contribute, all inputs are welcome!

**Comment by barodeur** [comment]
Haha @timstott, what does pranking mean? And how can I help you?

**Comment by timstott** [comment]
Hi @barodeur [this is pranking](https://www.youtube.com/watch?v=x-TvqL-0XGM) :smile:

All our design inspiration comes from the [following site](http://www.lingscars.com/). We're looking for some additional terrible design practices to implement. We're taking all idea in at the moment

**Comment by barodeur** [comment]
OMG, that website is terrible !
I'll be in London by the end of the week, I'll send you my PR from there ;)

2014-08-17 21:18 GMT+02:00 Timothy Stott notifications@github.com:

**Comment by MartinDesigner** [comment]
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
